apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traffic

resources:
  - namespace.yaml
  - secret.yaml
  - config/clickhouse-init-configmap.yaml
  - infra/postgres.yaml
  - infra/kafka.yaml
  - infra/clickhouse.yaml
  - infra/minio.yaml
  - infra/mediamtx.yaml
  - jobs/kafka-topics-init.yaml
  - jobs/clickhouse-init.yaml
  - jobs/minio-init.yaml
  - apps/coordinator.yaml
  - apps/analytics.yaml
  - apps/pusher.yaml
  - apps/data-service.yaml
  - apps/ml-serving.yaml
  - apps/router.yaml
  - apps/rtsp-generator.yaml
  - observability/prometheus-rbac.yaml
  - observability/prometheus-configmap.yaml
  - observability/prometheus-deployment.yaml
  - observability/grafana-datasources-configmap.yaml
  - observability/grafana-dashboards-configmap.yaml
  - observability/grafana-pvc.yaml
  - observability/grafana.yaml

configMapGenerator:
  - name: postgres-init
    files:
      - ../../infra/postgres/init/001_coordinator_schema.sql
      - ../../infra/postgres/init/002_coordinator_seed.sql
  - name: router-config
    files:
      - ../../services/router/config.cameras.docker.yaml
  - name: grafana-dashboards-json
    files:
      - traffic-services.json=../../infra/grafana/provisioning/dashboards/json/traffic-services.json
      - traffic-results.json=../../infra/grafana/provisioning/dashboards/json/traffic-results.json
