apiVersion: v1
kind: Secret
metadata:
  name: traffic-secrets
type: Opaque
stringData:
  postgres-user: coordinator
  postgres-password: coordinator
  postgres-db: coordinator
  minio-access-key: minioadmin
  minio-secret-key: minioadmin
