// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: api/map/v1/map_api.proto

package mapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MapPortal_ListMunicipalities_FullMethodName = "/map.v1.MapPortal/ListMunicipalities"
	MapPortal_ListStops_FullMethodName          = "/map.v1.MapPortal/ListStops"
	MapPortal_ListBuses_FullMethodName          = "/map.v1.MapPortal/ListBuses"
)

// MapPortalClient is the client API for MapPortal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Данные для map_portal: справочники из CH и автобусы в памяти analytics.
type MapPortalClient interface {
	ListMunicipalities(ctx context.Context, in *ListMunicipalitiesRequest, opts ...grpc.CallOption) (*ListMunicipalitiesResponse, error)
	ListStops(ctx context.Context, in *ListStopsRequest, opts ...grpc.CallOption) (*ListStopsResponse, error)
	ListBuses(ctx context.Context, in *ListBusesRequest, opts ...grpc.CallOption) (*ListBusesResponse, error)
}

type mapPortalClient struct {
	cc grpc.ClientConnInterface
}

func NewMapPortalClient(cc grpc.ClientConnInterface) MapPortalClient {
	return &mapPortalClient{cc}
}

func (c *mapPortalClient) ListMunicipalities(ctx context.Context, in *ListMunicipalitiesRequest, opts ...grpc.CallOption) (*ListMunicipalitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMunicipalitiesResponse)
	err := c.cc.Invoke(ctx, MapPortal_ListMunicipalities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapPortalClient) ListStops(ctx context.Context, in *ListStopsRequest, opts ...grpc.CallOption) (*ListStopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStopsResponse)
	err := c.cc.Invoke(ctx, MapPortal_ListStops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapPortalClient) ListBuses(ctx context.Context, in *ListBusesRequest, opts ...grpc.CallOption) (*ListBusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBusesResponse)
	err := c.cc.Invoke(ctx, MapPortal_ListBuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapPortalServer is the server API for MapPortal service.
// All implementations must embed UnimplementedMapPortalServer
// for forward compatibility.
//
// Данные для map_portal: справочники из CH и автобусы в памяти analytics.
type MapPortalServer interface {
	ListMunicipalities(context.Context, *ListMunicipalitiesRequest) (*ListMunicipalitiesResponse, error)
	ListStops(context.Context, *ListStopsRequest) (*ListStopsResponse, error)
	ListBuses(context.Context, *ListBusesRequest) (*ListBusesResponse, error)
	mustEmbedUnimplementedMapPortalServer()
}

// UnimplementedMapPortalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapPortalServer struct{}

func (UnimplementedMapPortalServer) ListMunicipalities(context.Context, *ListMunicipalitiesRequest) (*ListMunicipalitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMunicipalities not implemented")
}
func (UnimplementedMapPortalServer) ListStops(context.Context, *ListStopsRequest) (*ListStopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStops not implemented")
}
func (UnimplementedMapPortalServer) ListBuses(context.Context, *ListBusesRequest) (*ListBusesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuses not implemented")
}
func (UnimplementedMapPortalServer) mustEmbedUnimplementedMapPortalServer() {}
func (UnimplementedMapPortalServer) testEmbeddedByValue()                   {}

// UnsafeMapPortalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapPortalServer will
// result in compilation errors.
type UnsafeMapPortalServer interface {
	mustEmbedUnimplementedMapPortalServer()
}

func RegisterMapPortalServer(s grpc.ServiceRegistrar, srv MapPortalServer) {
	// If the following call pancis, it indicates UnimplementedMapPortalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MapPortal_ServiceDesc, srv)
}

func _MapPortal_ListMunicipalities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMunicipalitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapPortalServer).ListMunicipalities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapPortal_ListMunicipalities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapPortalServer).ListMunicipalities(ctx, req.(*ListMunicipalitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapPortal_ListStops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapPortalServer).ListStops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapPortal_ListStops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapPortalServer).ListStops(ctx, req.(*ListStopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapPortal_ListBuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapPortalServer).ListBuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapPortal_ListBuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapPortalServer).ListBuses(ctx, req.(*ListBusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MapPortal_ServiceDesc is the grpc.ServiceDesc for MapPortal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapPortal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "map.v1.MapPortal",
	HandlerType: (*MapPortalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMunicipalities",
			Handler:    _MapPortal_ListMunicipalities_Handler,
		},
		{
			MethodName: "ListStops",
			Handler:    _MapPortal_ListStops_Handler,
		},
		{
			MethodName: "ListBuses",
			Handler:    _MapPortal_ListBuses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/map/v1/map_api.proto",
}
