// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: api/map/v1/map_api.proto

package mapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMunicipalitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMunicipalitiesRequest) Reset() {
	*x = ListMunicipalitiesRequest{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMunicipalitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMunicipalitiesRequest) ProtoMessage() {}

func (x *ListMunicipalitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMunicipalitiesRequest.ProtoReflect.Descriptor instead.
func (*ListMunicipalitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{0}
}

type Municipality struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MunicipalityId string                 `protobuf:"bytes,1,opt,name=municipality_id,json=municipalityId,proto3" json:"municipality_id,omitempty"`
	NameRu         string                 `protobuf:"bytes,2,opt,name=name_ru,json=nameRu,proto3" json:"name_ru,omitempty"`
	CenterLat      float64                `protobuf:"fixed64,3,opt,name=center_lat,json=centerLat,proto3" json:"center_lat,omitempty"`
	CenterLon      float64                `protobuf:"fixed64,4,opt,name=center_lon,json=centerLon,proto3" json:"center_lon,omitempty"`
	DefaultZoom    uint32                 `protobuf:"varint,5,opt,name=default_zoom,json=defaultZoom,proto3" json:"default_zoom,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Municipality) Reset() {
	*x = Municipality{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Municipality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Municipality) ProtoMessage() {}

func (x *Municipality) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Municipality.ProtoReflect.Descriptor instead.
func (*Municipality) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{1}
}

func (x *Municipality) GetMunicipalityId() string {
	if x != nil {
		return x.MunicipalityId
	}
	return ""
}

func (x *Municipality) GetNameRu() string {
	if x != nil {
		return x.NameRu
	}
	return ""
}

func (x *Municipality) GetCenterLat() float64 {
	if x != nil {
		return x.CenterLat
	}
	return 0
}

func (x *Municipality) GetCenterLon() float64 {
	if x != nil {
		return x.CenterLon
	}
	return 0
}

func (x *Municipality) GetDefaultZoom() uint32 {
	if x != nil {
		return x.DefaultZoom
	}
	return 0
}

type ListMunicipalitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Municipality        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMunicipalitiesResponse) Reset() {
	*x = ListMunicipalitiesResponse{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMunicipalitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMunicipalitiesResponse) ProtoMessage() {}

func (x *ListMunicipalitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMunicipalitiesResponse.ProtoReflect.Descriptor instead.
func (*ListMunicipalitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListMunicipalitiesResponse) GetItems() []*Municipality {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListStopsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MunicipalityId string                 `protobuf:"bytes,1,opt,name=municipality_id,json=municipalityId,proto3" json:"municipality_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListStopsRequest) Reset() {
	*x = ListStopsRequest{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStopsRequest) ProtoMessage() {}

func (x *ListStopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStopsRequest.ProtoReflect.Descriptor instead.
func (*ListStopsRequest) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListStopsRequest) GetMunicipalityId() string {
	if x != nil {
		return x.MunicipalityId
	}
	return ""
}

type Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopId        string                 `protobuf:"bytes,1,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	StopCode      string                 `protobuf:"bytes,2,opt,name=stop_code,json=stopCode,proto3" json:"stop_code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameShort     string                 `protobuf:"bytes,4,opt,name=name_short,json=nameShort,proto3" json:"name_short,omitempty"`
	Lat           float64                `protobuf:"fixed64,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,6,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stop) Reset() {
	*x = Stop{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{4}
}

func (x *Stop) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *Stop) GetStopCode() string {
	if x != nil {
		return x.StopCode
	}
	return ""
}

func (x *Stop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stop) GetNameShort() string {
	if x != nil {
		return x.NameShort
	}
	return ""
}

func (x *Stop) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Stop) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type ListStopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Stop                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStopsResponse) Reset() {
	*x = ListStopsResponse{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStopsResponse) ProtoMessage() {}

func (x *ListStopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStopsResponse.ProtoReflect.Descriptor instead.
func (*ListStopsResponse) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListStopsResponse) GetItems() []*Stop {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListBusesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MunicipalityId string                 `protobuf:"bytes,1,opt,name=municipality_id,json=municipalityId,proto3" json:"municipality_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBusesRequest) Reset() {
	*x = ListBusesRequest{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBusesRequest) ProtoMessage() {}

func (x *ListBusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBusesRequest.ProtoReflect.Descriptor instead.
func (*ListBusesRequest) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListBusesRequest) GetMunicipalityId() string {
	if x != nil {
		return x.MunicipalityId
	}
	return ""
}

type Bus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VehicleId         string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	RouteId           string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Lat               float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon               float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	SpeedKmh          float64                `protobuf:"fixed64,5,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	HeadingDeg        float64                `protobuf:"fixed64,6,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	ObservedAtRfc3339 string                 `protobuf:"bytes,7,opt,name=observed_at_rfc3339,json=observedAtRfc3339,proto3" json:"observed_at_rfc3339,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Bus) Reset() {
	*x = Bus{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bus) ProtoMessage() {}

func (x *Bus) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bus.ProtoReflect.Descriptor instead.
func (*Bus) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{7}
}

func (x *Bus) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Bus) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Bus) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Bus) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Bus) GetSpeedKmh() float64 {
	if x != nil {
		return x.SpeedKmh
	}
	return 0
}

func (x *Bus) GetHeadingDeg() float64 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *Bus) GetObservedAtRfc3339() string {
	if x != nil {
		return x.ObservedAtRfc3339
	}
	return ""
}

type ListBusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Bus                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBusesResponse) Reset() {
	*x = ListBusesResponse{}
	mi := &file_api_map_v1_map_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBusesResponse) ProtoMessage() {}

func (x *ListBusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_map_v1_map_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBusesResponse.ProtoReflect.Descriptor instead.
func (*ListBusesResponse) Descriptor() ([]byte, []int) {
	return file_api_map_v1_map_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListBusesResponse) GetItems() []*Bus {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_map_v1_map_api_proto protoreflect.FileDescriptor

const file_api_map_v1_map_api_proto_rawDesc = "" +
	"\n" +
	"\x18api/map/v1/map_api.proto\x12\x06map.v1\"\x1b\n" +
	"\x19ListMunicipalitiesRequest\"\xb1\x01\n" +
	"\fMunicipality\x12'\n" +
	"\x0fmunicipality_id\x18\x01 \x01(\tR\x0emunicipalityId\x12\x17\n" +
	"\aname_ru\x18\x02 \x01(\tR\x06nameRu\x12\x1d\n" +
	"\n" +
	"center_lat\x18\x03 \x01(\x01R\tcenterLat\x12\x1d\n" +
	"\n" +
	"center_lon\x18\x04 \x01(\x01R\tcenterLon\x12!\n" +
	"\fdefault_zoom\x18\x05 \x01(\rR\vdefaultZoom\"H\n" +
	"\x1aListMunicipalitiesResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.map.v1.MunicipalityR\x05items\";\n" +
	"\x10ListStopsRequest\x12'\n" +
	"\x0fmunicipality_id\x18\x01 \x01(\tR\x0emunicipalityId\"\x93\x01\n" +
	"\x04Stop\x12\x17\n" +
	"\astop_id\x18\x01 \x01(\tR\x06stopId\x12\x1b\n" +
	"\tstop_code\x18\x02 \x01(\tR\bstopCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"name_short\x18\x04 \x01(\tR\tnameShort\x12\x10\n" +
	"\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x06 \x01(\x01R\x03lon\"7\n" +
	"\x11ListStopsResponse\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.map.v1.StopR\x05items\";\n" +
	"\x10ListBusesRequest\x12'\n" +
	"\x0fmunicipality_id\x18\x01 \x01(\tR\x0emunicipalityId\"\xd1\x01\n" +
	"\x03Bus\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x1b\n" +
	"\tspeed_kmh\x18\x05 \x01(\x01R\bspeedKmh\x12\x1f\n" +
	"\vheading_deg\x18\x06 \x01(\x01R\n" +
	"headingDeg\x12.\n" +
	"\x13observed_at_rfc3339\x18\a \x01(\tR\x11observedAtRfc3339\"6\n" +
	"\x11ListBusesResponse\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.map.v1.BusR\x05items2\xec\x01\n" +
	"\tMapPortal\x12[\n" +
	"\x12ListMunicipalities\x12!.map.v1.ListMunicipalitiesRequest\x1a\".map.v1.ListMunicipalitiesResponse\x12@\n" +
	"\tListStops\x12\x18.map.v1.ListStopsRequest\x1a\x19.map.v1.ListStopsResponse\x12@\n" +
	"\tListBuses\x12\x18.map.v1.ListBusesRequest\x1a\x19.map.v1.ListBusesResponseB$Z\"traffic-analytics/api/map/v1;mapv1b\x06proto3"

var (
	file_api_map_v1_map_api_proto_rawDescOnce sync.Once
	file_api_map_v1_map_api_proto_rawDescData []byte
)

func file_api_map_v1_map_api_proto_rawDescGZIP() []byte {
	file_api_map_v1_map_api_proto_rawDescOnce.Do(func() {
		file_api_map_v1_map_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_map_v1_map_api_proto_rawDesc), len(file_api_map_v1_map_api_proto_rawDesc)))
	})
	return file_api_map_v1_map_api_proto_rawDescData
}

var file_api_map_v1_map_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_map_v1_map_api_proto_goTypes = []any{
	(*ListMunicipalitiesRequest)(nil),  // 0: map.v1.ListMunicipalitiesRequest
	(*Municipality)(nil),               // 1: map.v1.Municipality
	(*ListMunicipalitiesResponse)(nil), // 2: map.v1.ListMunicipalitiesResponse
	(*ListStopsRequest)(nil),           // 3: map.v1.ListStopsRequest
	(*Stop)(nil),                       // 4: map.v1.Stop
	(*ListStopsResponse)(nil),          // 5: map.v1.ListStopsResponse
	(*ListBusesRequest)(nil),           // 6: map.v1.ListBusesRequest
	(*Bus)(nil),                        // 7: map.v1.Bus
	(*ListBusesResponse)(nil),          // 8: map.v1.ListBusesResponse
}
var file_api_map_v1_map_api_proto_depIdxs = []int32{
	1, // 0: map.v1.ListMunicipalitiesResponse.items:type_name -> map.v1.Municipality
	4, // 1: map.v1.ListStopsResponse.items:type_name -> map.v1.Stop
	7, // 2: map.v1.ListBusesResponse.items:type_name -> map.v1.Bus
	0, // 3: map.v1.MapPortal.ListMunicipalities:input_type -> map.v1.ListMunicipalitiesRequest
	3, // 4: map.v1.MapPortal.ListStops:input_type -> map.v1.ListStopsRequest
	6, // 5: map.v1.MapPortal.ListBuses:input_type -> map.v1.ListBusesRequest
	2, // 6: map.v1.MapPortal.ListMunicipalities:output_type -> map.v1.ListMunicipalitiesResponse
	5, // 7: map.v1.MapPortal.ListStops:output_type -> map.v1.ListStopsResponse
	8, // 8: map.v1.MapPortal.ListBuses:output_type -> map.v1.ListBusesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_map_v1_map_api_proto_init() }
func file_api_map_v1_map_api_proto_init() {
	if File_api_map_v1_map_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_map_v1_map_api_proto_rawDesc), len(file_api_map_v1_map_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_map_v1_map_api_proto_goTypes,
		DependencyIndexes: file_api_map_v1_map_api_proto_depIdxs,
		MessageInfos:      file_api_map_v1_map_api_proto_msgTypes,
	}.Build()
	File_api_map_v1_map_api_proto = out.File
	file_api_map_v1_map_api_proto_goTypes = nil
	file_api_map_v1_map_api_proto_depIdxs = nil
}
