// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/road_congestion": {
            "get": {
                "summary": "Список записей road_congestion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по segment_id",
                        "name": "segment_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по camera_id",
                        "name": "camera_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит строк (по умолчанию 100, макс. 500)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.RoadCongestionListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/road_incidents": {
            "get": {
                "summary": "Список записей road_incidents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по segment_id",
                        "name": "segment_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по camera_id",
                        "name": "camera_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит строк (по умолчанию 100, макс. 500)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.RoadIncidentsListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "summary": "Liveness / health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.ProbeResponse"
                        }
                    }
                }
            }
        },
        "/probe/health": {
            "get": {
                "summary": "Health (probe path)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.ProbeResponse"
                        }
                    }
                }
            }
        },
        "/probe/ready": {
            "get": {
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data-service_internal_adapters_http_dto.ProbeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "data-service_internal_adapters_http_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "data-service_internal_adapters_http_dto.ProbeResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "data-service_internal_adapters_http_dto.RoadCongestionItem": {
            "type": "object",
            "properties": {
                "camera_id": {
                    "type": "string"
                },
                "congestion_score": {
                    "type": "number"
                },
                "observed_at": {
                    "type": "string"
                },
                "raw_ml": {
                    "type": "string"
                },
                "s3_key": {
                    "type": "string"
                },
                "segment_id": {
                    "type": "string"
                }
            }
        },
        "data-service_internal_adapters_http_dto.RoadCongestionListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data-service_internal_adapters_http_dto.RoadCongestionItem"
                    }
                }
            }
        },
        "data-service_internal_adapters_http_dto.RoadIncidentItem": {
            "type": "object",
            "properties": {
                "camera_id": {
                    "type": "string"
                },
                "crash_probability": {
                    "type": "number"
                },
                "incident_label": {
                    "type": "string"
                },
                "observed_at": {
                    "type": "string"
                },
                "raw_ml": {
                    "type": "string"
                },
                "s3_key": {
                    "type": "string"
                },
                "segment_id": {
                    "type": "string"
                }
            }
        },
        "data-service_internal_adapters_http_dto.RoadIncidentsListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data-service_internal_adapters_http_dto.RoadIncidentItem"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ITS Data Service API",
	Description:      "HTTP API: health/probe, чтение ClickHouse road_incidents и road_congestion, Swagger.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
