// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/get_product": {
            "get": {
                "summary": "Get product creation by product ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductCreation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.GetProductResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.GetProductResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GetProductResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "summary": "Liveness / health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProbeResponse"
                        }
                    }
                }
            }
        },
        "/probe/health": {
            "get": {
                "summary": "Health (probe path)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProbeResponse"
                        }
                    }
                }
            }
        },
        "/probe/ready": {
            "get": {
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProbeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.GetProductResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.ProbeResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "dto.ProductCreation": {
            "type": "object",
            "properties": {
                "bad_presets": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "duration": {
                    "type": "integer"
                },
                "end_timestamp": {
                    "type": "string"
                },
                "force_trigger": {
                    "type": "boolean"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "preset_conversions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "preset_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "preset_requireds": {
                    "type": "array",
                    "items": {
                        "type": "boolean"
                    }
                },
                "preset_scores": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "presets": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "product_id": {
                    "type": "integer"
                },
                "published_product_presets": {
                    "type": "integer"
                },
                "published_product_zero_presets": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "trace_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Trace Data Service API",
	Description:      "HTTP API trace-data-service: GET /health и GET /probe/health (liveness), GET /probe/ready (readiness), GET /swagger и /swagger/* (Swagger UI и OpenAPI).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
