// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "data-service/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockProductGetter is an autogenerated mock type for the ProductGetter type
type MockProductGetter struct {
	mock.Mock
}

type MockProductGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductGetter) EXPECT() *MockProductGetter_Expecter {
	return &MockProductGetter_Expecter{mock: &_m.Mock}
}

// GetProductCreation provides a mock function with given fields: ctx, productID
func (_m *MockProductGetter) GetProductCreation(ctx context.Context, productID int64) (*domain.ProductCreation, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductCreation")
	}

	var r0 *domain.ProductCreation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.ProductCreation, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.ProductCreation); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductCreation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductGetter_GetProductCreation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductCreation'
type MockProductGetter_GetProductCreation_Call struct {
	*mock.Call
}

// GetProductCreation is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int64
func (_e *MockProductGetter_Expecter) GetProductCreation(ctx interface{}, productID interface{}) *MockProductGetter_GetProductCreation_Call {
	return &MockProductGetter_GetProductCreation_Call{Call: _e.mock.On("GetProductCreation", ctx, productID)}
}

func (_c *MockProductGetter_GetProductCreation_Call) Run(run func(ctx context.Context, productID int64)) *MockProductGetter_GetProductCreation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProductGetter_GetProductCreation_Call) Return(_a0 *domain.ProductCreation, _a1 error) *MockProductGetter_GetProductCreation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductGetter_GetProductCreation_Call) RunAndReturn(run func(context.Context, int64) (*domain.ProductCreation, error)) *MockProductGetter_GetProductCreation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductGetter creates a new instance of MockProductGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductGetter {
	mock := &MockProductGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
