// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: api/bus/v1/telemetry.proto

package busv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BusTelemetryService_SendBusTelemetry_FullMethodName = "/bus.v1.BusTelemetryService/SendBusTelemetry"
)

// BusTelemetryServiceClient is the client API for BusTelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusTelemetryServiceClient interface {
	SendBusTelemetry(ctx context.Context, in *BusTelemetry, opts ...grpc.CallOption) (*SendBusTelemetryResponse, error)
}

type busTelemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusTelemetryServiceClient(cc grpc.ClientConnInterface) BusTelemetryServiceClient {
	return &busTelemetryServiceClient{cc}
}

func (c *busTelemetryServiceClient) SendBusTelemetry(ctx context.Context, in *BusTelemetry, opts ...grpc.CallOption) (*SendBusTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBusTelemetryResponse)
	err := c.cc.Invoke(ctx, BusTelemetryService_SendBusTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusTelemetryServiceServer is the server API for BusTelemetryService service.
// All implementations must embed UnimplementedBusTelemetryServiceServer
// for forward compatibility.
type BusTelemetryServiceServer interface {
	SendBusTelemetry(context.Context, *BusTelemetry) (*SendBusTelemetryResponse, error)
	mustEmbedUnimplementedBusTelemetryServiceServer()
}

// UnimplementedBusTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusTelemetryServiceServer struct{}

func (UnimplementedBusTelemetryServiceServer) SendBusTelemetry(context.Context, *BusTelemetry) (*SendBusTelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBusTelemetry not implemented")
}
func (UnimplementedBusTelemetryServiceServer) mustEmbedUnimplementedBusTelemetryServiceServer() {}
func (UnimplementedBusTelemetryServiceServer) testEmbeddedByValue()                             {}

// UnsafeBusTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusTelemetryServiceServer will
// result in compilation errors.
type UnsafeBusTelemetryServiceServer interface {
	mustEmbedUnimplementedBusTelemetryServiceServer()
}

func RegisterBusTelemetryServiceServer(s grpc.ServiceRegistrar, srv BusTelemetryServiceServer) {
	// If the following call pancis, it indicates UnimplementedBusTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BusTelemetryService_ServiceDesc, srv)
}

func _BusTelemetryService_SendBusTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusTelemetry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusTelemetryServiceServer).SendBusTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusTelemetryService_SendBusTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusTelemetryServiceServer).SendBusTelemetry(ctx, req.(*BusTelemetry))
	}
	return interceptor(ctx, in, info, handler)
}

// BusTelemetryService_ServiceDesc is the grpc.ServiceDesc for BusTelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusTelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bus.v1.BusTelemetryService",
	HandlerType: (*BusTelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBusTelemetry",
			Handler:    _BusTelemetryService_SendBusTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bus/v1/telemetry.proto",
}
