// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: api/bus/v1/telemetry.proto

package busv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BusTelemetry — периодическая телеметрия ТС (не ML).
type BusTelemetry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SegmentId         string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	VehicleId         string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	RouteId           string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Lat               float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon               float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`
	SpeedKmh          float64                `protobuf:"fixed64,6,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	HeadingDeg        float64                `protobuf:"fixed64,7,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	ObservedAtRfc3339 string                 `protobuf:"bytes,8,opt,name=observed_at_rfc3339,json=observedAtRfc3339,proto3" json:"observed_at_rfc3339,omitempty"`
	// Код города для карты и map_portal (msk, spb, kzn, ekb).
	MunicipalityId string `protobuf:"bytes,9,opt,name=municipality_id,json=municipalityId,proto3" json:"municipality_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BusTelemetry) Reset() {
	*x = BusTelemetry{}
	mi := &file_api_bus_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusTelemetry) ProtoMessage() {}

func (x *BusTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusTelemetry.ProtoReflect.Descriptor instead.
func (*BusTelemetry) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *BusTelemetry) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *BusTelemetry) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *BusTelemetry) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *BusTelemetry) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *BusTelemetry) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *BusTelemetry) GetSpeedKmh() float64 {
	if x != nil {
		return x.SpeedKmh
	}
	return 0
}

func (x *BusTelemetry) GetHeadingDeg() float64 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *BusTelemetry) GetObservedAtRfc3339() string {
	if x != nil {
		return x.ObservedAtRfc3339
	}
	return ""
}

func (x *BusTelemetry) GetMunicipalityId() string {
	if x != nil {
		return x.MunicipalityId
	}
	return ""
}

type SendBusTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBusTelemetryResponse) Reset() {
	*x = SendBusTelemetryResponse{}
	mi := &file_api_bus_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBusTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBusTelemetryResponse) ProtoMessage() {}

func (x *SendBusTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBusTelemetryResponse.ProtoReflect.Descriptor instead.
func (*SendBusTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

var File_api_bus_v1_telemetry_proto protoreflect.FileDescriptor

const file_api_bus_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/bus/v1/telemetry.proto\x12\x06bus.v1\"\xa2\x02\n" +
	"\fBusTelemetry\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x01R\x03lon\x12\x1b\n" +
	"\tspeed_kmh\x18\x06 \x01(\x01R\bspeedKmh\x12\x1f\n" +
	"\vheading_deg\x18\a \x01(\x01R\n" +
	"headingDeg\x12.\n" +
	"\x13observed_at_rfc3339\x18\b \x01(\tR\x11observedAtRfc3339\x12'\n" +
	"\x0fmunicipality_id\x18\t \x01(\tR\x0emunicipalityId\"\x1a\n" +
	"\x18SendBusTelemetryResponse2a\n" +
	"\x13BusTelemetryService\x12J\n" +
	"\x10SendBusTelemetry\x12\x14.bus.v1.BusTelemetry\x1a .bus.v1.SendBusTelemetryResponseB!Z\x1fdata-ingestion/api/bus/v1;busv1b\x06proto3"

var (
	file_api_bus_v1_telemetry_proto_rawDescOnce sync.Once
	file_api_bus_v1_telemetry_proto_rawDescData []byte
)

func file_api_bus_v1_telemetry_proto_rawDescGZIP() []byte {
	file_api_bus_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_api_bus_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bus_v1_telemetry_proto_rawDesc), len(file_api_bus_v1_telemetry_proto_rawDesc)))
	})
	return file_api_bus_v1_telemetry_proto_rawDescData
}

var file_api_bus_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_bus_v1_telemetry_proto_goTypes = []any{
	(*BusTelemetry)(nil),             // 0: bus.v1.BusTelemetry
	(*SendBusTelemetryResponse)(nil), // 1: bus.v1.SendBusTelemetryResponse
}
var file_api_bus_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: bus.v1.BusTelemetryService.SendBusTelemetry:input_type -> bus.v1.BusTelemetry
	1, // 1: bus.v1.BusTelemetryService.SendBusTelemetry:output_type -> bus.v1.SendBusTelemetryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_bus_v1_telemetry_proto_init() }
func file_api_bus_v1_telemetry_proto_init() {
	if File_api_bus_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bus_v1_telemetry_proto_rawDesc), len(file_api_bus_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bus_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_api_bus_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_api_bus_v1_telemetry_proto_msgTypes,
	}.Build()
	File_api_bus_v1_telemetry_proto = out.File
	file_api_bus_v1_telemetry_proto_goTypes = nil
	file_api_bus_v1_telemetry_proto_depIdxs = nil
}
